version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: America/Toronto
  open-pull-requests-limit: 10
  reviewers:
  - yi-nlmatics
  - tomliu7
  - kiran-nlmatics
  ignore:
  - dependency-name: nltk
    versions:
    - "3.6"
